[build]
  command = "npm run build && rm -rf netlify/functions/dist && cp -R dist netlify/functions/dist"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

[[redirects]]
  from = "/telegram-webhook"
  to = "/.netlify/functions/telegram-webhook-background"
  status = 200
